using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Game08Button : MonoBehaviour{

    public GameObject unpressed;
    public GameObject pressed;

    // Start is called before the first frame update
    void Start(){
        
    }

    // Update is called once per frame
    void Update(){
        
    }

    void OnTriggerStay2D(Collider2D col){
        if (Input.GetKeyDown(KeyCode.Space)){
            pressed.SetActive(true);
            unpressed.SetActive(false);
        }
    }
}
